### ISSUE TITLE
Stuck on too many redirects

### ISSUE THREAD

**Issue by peptolab** [nilsenpaul/npeditmultipleelements#4]
Installed from Plugin Store on Craft CMS 3 and tried to multiple edit 2 entries.

Results in an infinite looped redirect on multiple browsers.

Safari reports:

XMLHttpRequest cannot load http://[my server]/index.php?p=admin/actions/users/get-remaining-session-time&dontExtendSession=1 due to access control checks.
send - jquery.jsL9566
ajax - jquery.js:9173
checkRemainingSessionTime - Craft.js:9206

**Comment by nilsenpaul** [comment]
@peptolab The action that doesn't load, is a 'default' Craft action that checks if you're still logged in. I doubt that that is the problem here. It does, however, point out that there is a discrepancy between the url you use to access Craft, and the url Craft uses.

Could you please use your browser's devtools to see what redirection is happening? We need some more info to get to a solution.

**Comment by nilsenpaul** [comment]
Also: could you post this issue in the right place: https://github.com/nilsenpaul/craft-sequentialedit/issues, as that's where the Craft 3 plugin lives?
